# Basic
title: DREAM
subtitle: Blog
description: æ¬¢è¿æ¥åˆ°Â·MeÂ·ä¸ªäººç«™~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: DREAM
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: ç”µæ°” / ROBOT
url: "http://DREAM531953845.io"

# Comment
# disqusã€uyanè¯·é€‰æ‹©å…¶ä¸€ #
comment:
    disqus: xxxxx # disqusè¯„è®º idï¼Œç™»é™†disquså®˜ç½‘ç”³è¯·
    uyan: xxxxx  # æœ‰è¨€è¯„è®º id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·

# Social
social:
    #weibo: xxxxx # Weibo id
    github: DREAM531953845 # Github id
    #twitter: xxxxx # Twitter id
    mail: 531953845@qq.com # E-Mail id

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id: xxxxxxxxxx # ç™¾åº¦ç»Ÿè®¡ id

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id: xxxxxxxxxx # Google Analytics ç»Ÿè®¡ id
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/DREAM531953845/DREAM531953845.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


